apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-deployment
spec:
  selector:
    matchLabels:
      app: pace
  replicas: 2
  template:
    metadata:
      labels:
        app: pace
    spec:
      containers:
        - name: pace
          image: oajojjj/pace:latest
          ports:
            - containerPort: 8080
