apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-deployment
spec:
    selector:
      matchlabels: 
        app: pace
  replicas: 3
  template:
    metadata:
      labels:
        app: pace
    spec:
      containers:
      - name: pace
        image: oajojjj/pace:latest
        ports:
        - containerPort: 80
