name: Repository Dispatch
on:
  repository_dispatch:
    types: [update]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'deployment.yaml'
          propertyPath: 'spec.template.spec.containers.image'
          value: 'oajojjj/pace:${{ github.event.client_payload.TAG }}'
          branch: main
          message: 'Updated image version to ${{ github.event.client_payload.TAG }}'
